name: Build and Deploy Microservice APIs

on:
  push:
    branches: master

jobs:
   test:
    name: Nessus
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x ]
    steps:
     - uses: actions/checkout@v2
       with:
          fetch-depth: 0 
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v2
       with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
     - run: npm i
     - name: Build
       run: npm run build
       env:
          CI: false
     #- run: npm test integration
     
     - uses: actions/checkout@v3

     - name: Build Docker Image
       run: docker image build . --file Dockerfile --tag ciromota/nessus-scanner:latest

     - name: Run Trivy vulnerability scanner
       uses: aquasecurity/trivy-action@master
       with:
          image-ref: 'ciromota/nessus-scanner:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
   
